In [1]:
# Import Packages
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import SMOTE
pd.set_option('display.max_columns', 300)
% matplotlib inline

plt.style.use('seaborn')

In [2]:
exp_df = pd.read_csv('experiment_features.csv',index_col=0)
exp_df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  prolongued_decelerations  \
0                0.000                       0.0   
1                0.003                       0.0   
2                0.003                       0.0   
3                0.003                       0.0   
4                0.000                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  \
0                                               43.0        
1                                                0.0        
2                                                0.0        
3                                                0.0        
4                                                0.0        

   mean_value_of_long_term_variability  histogram_width  histogram_min  \
0                                  2.4             64.0           62.0   
1                                 10.4            130.0           68.0   
2                                 13.4            130.0           68.0   
3                                 23.0            117.0           53.0   
4                                 19.9            117.0           53.0   

   histogram_max  histogram_number_of_peaks  histogram_mode  histogram_mean  \
0          126.0                        2.0           120.0           137.0   
1          198.0                        6.0           141.0           136.0   
2          198.0                        5.0           141.0           135.0   
3          170.0                       11.0           137.0           134.0   
4          170.0                        9.0           137.0           136.0   

   histogram_median  histogram_variance  fetal_health  uterine_cont_per_min  \
0             121.0                73.0           2.0                  0.00   
1             140.0                12.0           1.0                  0.36   
2             138.0                13.0           1.0                  0.48   
3             137.0                13.0           1.0                  0.48   
4             138.0                11.0           1.0                  0.48   

   total_change  sqrt_total_change  hist_zeros_1.0  hist_zeros_2.0  \
0         0.000           0.000000               0               0   
1         1.980           0.122474               1               0   
2         1.862           0.118322               1               0   
3         1.876           0.118322               0               0   
4         1.980           0.122474               0               0   

   hist_zeros_3.0  hist_zeros_4.0  hist_zeros_5.0  hist_zeros_7.0  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   hist_zeros_8.0  hist_zeros_10.0  hist_tendancy_0.0  hist_tendancy_1.0  \
0               0                0                  0                  1   
1               0                0    

In [3]:
# Evaluation function
def evaluation(y_test, y_pred):
    print('Accuracy: '  + str(metrics.accuracy_score(y_test, y_pred)))
    print('Recall: ' + str(metrics.recall_score(y_test, y_pred)))
    print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred)))
    print('Precision: ' + str(metrics.precision_score(y_test, y_pred)))

In [4]:
X = exp_df.drop('fetal_health', axis =1)
y = exp_df.fetal_health

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=1)

In [8]:
sm = SMOTE(random_state=25)
smX_train, smy_train = sm.fit_sample(X_train, y_train)

In [5]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [6]:
y_pred = knn.predict(X_test)

In [7]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[396  13]
 [ 31  92]]
Accuracy: 0.9172932330827067
Recall: 0.9682151589242054
F1 Score: 0.9473684210526316
Precision: 0.927400468384075


In [23]:
smknn = KNeighborsClassifier(n_neighbors=1)
smknn.fit(smX_train,smy_train)


KNeighborsClassifier(n_neighbors=1)

In [24]:
y_pred = smknn.predict(X_test)

In [25]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[392  17]
 [ 27  96]]
Accuracy: 0.9172932330827067
Recall: 0.9584352078239609
F1 Score: 0.9468599033816426
Precision: 0.9355608591885441


In [11]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

/Users/heymanjake/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [12]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[385  24]
 [ 41  82]]
Accuracy: 0.8778195488721805
Recall: 0.941320293398533
F1 Score: 0.9221556886227544
Precision: 0.903755868544601


In [28]:
smlr = LogisticRegression(solver='liblinear')
smlr.fit(smX_train,smy_train)
y_pred = smlr.predict(X_test)

In [29]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[360  49]
 [ 12 111]]
Accuracy: 0.8853383458646616
Recall: 0.8801955990220048
F1 Score: 0.9218950064020486
Precision: 0.967741935483871


In [55]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",lr.coef_.transpose())

coef_table_2 = pd.DataFrame(list(smX_train.columns)).copy()
coef_table_2.insert(len(coef_table_2.columns),'sm_Coefs',smlr.coef_.transpose())

smote_vs_coef = pd.concat([coef_table,coef_table_2],axis=1)
smote_vs_coef.columns = ['features','Coefs','del','sm_Coefs']
del smote_vs_coef['del']
smote_vs_coef

features     Coefs  sm_Coefs
0                                      baseline value  0.113120  0.112113
1                                       accelerations -0.003969 -0.224252
2                                      fetal_movement  0.010522  0.313262
3                                uterine_contractions -0.005162 -0.055485
4                                 light_decelerations -0.002154 -0.036389
5                            prolongued_decelerations  0.000782  0.044586
6                     abnormal_short_term_variability  0.066839  0.084350
7                mean_value_of_short_term_variability -0.693801 -0.626913
8   percentage_of_time_with_abnormal_long_term_var...  0.037477  0.039607
9                 mean_value_of_long_term_variability  0.028837  0.045947
10                                    histogram_width -0.013946 -0.009616
11                                      histogram_min  0.006153 -0.001040
12                                      histogram_max -0.007793 -0.010656
13                          histogram_number_of_peaks  0.244309  0.200837
14                                     histogram_mode -0.023229 -0.009779
15                                     histogram_mean  0.032644 -0.059707
16                                   histogram_median -0.151405 -0.031339
17                                 histogram_variance  0.034358  0.045463
18                               uterine_cont_per_min -0.309725 -3.329097
19                                       total_change  0.039740  0.062281
20                                  sqrt_total_change -0.047973 -1.245735
21                                     hist_zeros_1.0  0.062708 -0.514483
22                                     hist_zeros_2.0  0.019549 -0.583633
23                                     hist_zeros_3.0 -0.002612 -1.085404
24                                     hist_zeros_4.0  0.017099  0.384853
25                                     hist_zeros_5.0 -0.002186 -0.626686
26                                     hist_zeros_7.0  0.000000  0.000000
27                                     hist_zeros_8.0  0.010689  0.195844
28                                    hist_zeros_10.0 -0.000754 -0.629847
29                                  hist_tendancy_0.0 -0.074347 -0.752577
30                                  hist_tendancy_1.0  0.089237 -1.254315
31                                    sev_decel_0.001 -0.003674 -0.238835
32                                        quant_acc_1 -0.228908 -3.312252
33                                  quant_light_dec_1 -0.334317 -1.669820
34                                  quant_hist_mean_1 -0.453605 -2.735225
35                                  quant_hist_mean_2 -0.247558 -2.348351
36                                  quant_hist_mean_3 -0.345706 -2.624426
37                                  quant_hist_mean_4  0.054543 -1.194180
38                                  quant_hist_mean_5  0.415893 -0.125200
39                                  quant_hist_mean_6  0.580439  0.816205

In [14]:
tree = DecisionTreeClassifier()

tree = tree.fit(X_train,y_train)

y_pred = tree.predict(X_test)

In [15]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[386  23]
 [ 19 104]]
Accuracy: 0.9210526315789473
Recall: 0.9437652811735942
F1 Score: 0.9484029484029485
Precision: 0.9530864197530864


In [57]:
smtree = DecisionTreeClassifier()
smtree.fit(smX_train,smy_train)
y_pred = smtree.predict(X_test)

In [58]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[394  15]
 [ 18 105]]
Accuracy: 0.9379699248120301
Recall: 0.9633251833740831
F1 Score: 0.9598051157125458
Precision: 0.9563106796116505


In [61]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",tree.feature_importances_.transpose())

coef_table_2 = pd.DataFrame(list(smX_train.columns)).copy()
coef_table_2.insert(len(coef_table_2.columns),'sm_Coefs',tree.feature_importances_.transpose())

smote_vs_coef = pd.concat([coef_table,coef_table_2],axis=1)
smote_vs_coef.columns = ['features','importance','del','sm_importance']
del smote_vs_coef['del']
smote_vs_coef

features  importance  \
0                                      baseline value    0.057821   
1                                       accelerations    0.019693   
2                                      fetal_movement    0.004742   
3                                uterine_contractions    0.012571   
4                                 light_decelerations    0.000000   
5                            prolongued_decelerations    0.028585   
6                     abnormal_short_term_variability    0.343378   
7                mean_value_of_short_term_variability    0.114219   
8   percentage_of_time_with_abnormal_long_term_var...    0.041862   
9                 mean_value_of_long_term_variability    0.012696   
10                                    histogram_width    0.023011   
11                                      histogram_min    0.038357   
12                                      histogram_max    0.028403   
13                          histogram_number_of_peaks    0.016263   
14                                     histogram_mode    0.025144   
15                                     histogram_mean    0.170278   
16                                   histogram_median    0.006113   
17                                 histogram_variance    0.006461   
18                               uterine_cont_per_min    0.000000   
19                                       total_change    0.037488   
20                                  sqrt_total_change    0.006027   
21                                     hist_zeros_1.0    0.000000   
22                                     hist_zeros_2.0    0.000000   
23                                     hist_zeros_3.0    0.000000   
24                                     hist_zeros_4.0    0.003614   
25                                     hist_zeros_5.0    0.000000   
26                                     hist_zeros_7.0    0.000000   
27                                     hist_zeros_8.0    0.000000   
28                                    hist_zeros_10.0    0.000000   
29                                  hist_tendancy_0.0    0.000000   
30                                  hist_tendancy_1.0    0.000000   
31                                    sev_decel_0.001    0.000000   
32                                        quant_acc_1    0.000000   
33                                  quant_light_dec_1    0.000000   
34                                  quant_hist_mean_1    0.000000   
35                                  quant_hist_mean_2    0.003274   
36                                  quant_hist_mean_3    0.000000   
37                                  quant_hist_mean_4    0.000000   
38                                  quant_hist_mean_5    0.000000   
39                                  quant_hist_mean_6    0.000000   

    sm_importance  
0        0.057821  
1        0.019693  
2        0.004742  
3        0.012571  
4        0.000000  
5        0.028585  
6        0.343378  
7        0.114219  
8        0.041862  
9        0.012696  
10       0.023011  
11       0.038357  
12       0.028403  
13       0.016263  
14       0.025144  
15       0.170278  
16       0.006113  
17       0.006461  
18       0.000000  
19       0.037488  
20       0.006027  
21       0.000000  
22       0.000000  
23       0.000000  
24       0.003614  
25       0.000000  
26       0.000000  
27       0.000000  
28       0.000000  
29       0.000000  
30       0.000000  
31       0.000000  
32       0.000000  
33       0.000000  
34       0.000000  
35       0.003274  
36       0.000000  
37       0.000000  
38       0.000000  
39       0.000000

In [17]:
rfc = RandomForestClassifier(random_state =1, n_estimators= 50, max_depth = 3, n_jobs =-1,verbose=1)
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  50 out of  50 | elapsed:    0.0s finished


In [18]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[402   7]
 [ 46  77]]
Accuracy: 0.900375939849624
Recall: 0.9828850855745721
F1 Score: 0.9381563593932323
Precision: 0.8973214285714286


In [19]:
param_grid = {'n_estimators'}