In [110]:
# Import Packages
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from sklearn.ensemble import BaggingClassifier
pd.set_option('display.max_columns', 300)
% matplotlib inline

plt.style.use('seaborn')

In [2]:
exp_df = pd.read_csv('experiment_features.csv',index_col=0)
exp_df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  prolongued_decelerations  \
0                0.000                       0.0   
1                0.003                       0.0   
2                0.003                       0.0   
3                0.003                       0.0   
4                0.000                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  \
0                                               43.0        
1                                                0.0        
2                                                0.0        
3                                                0.0        
4                                                0.0        

   mean_value_of_long_term_variability  histogram_width  histogram_min  \
0                                  2.4             64.0           62.0   
1                                 10.4            130.0           68.0   
2                                 13.4            130.0           68.0   
3                                 23.0            117.0           53.0   
4                                 19.9            117.0           53.0   

   histogram_max  histogram_number_of_peaks  histogram_mode  histogram_mean  \
0          126.0                        2.0           120.0           137.0   
1          198.0                        6.0           141.0           136.0   
2          198.0                        5.0           141.0           135.0   
3          170.0                       11.0           137.0           134.0   
4          170.0                        9.0           137.0           136.0   

   histogram_median  histogram_variance  fetal_health  uterine_cont_per_min  \
0             121.0                73.0           2.0                  0.00   
1             140.0                12.0           1.0                  0.36   
2             138.0                13.0           1.0                  0.48   
3             137.0                13.0           1.0                  0.48   
4             138.0                11.0           1.0                  0.48   

   total_change  sqrt_total_change  hist_zeros_1.0  hist_zeros_2.0  \
0         0.000           0.000000               0               0   
1         1.980           0.122474               1               0   
2         1.862           0.118322               1               0   
3         1.876           0.118322               0               0   
4         1.980           0.122474               0               0   

   hist_zeros_3.0  hist_zeros_4.0  hist_zeros_5.0  hist_zeros_7.0  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   hist_zeros_8.0  hist_zeros_10.0  hist_tendancy_0.0  hist_tendancy_1.0  \
0               0                0                  0                  1   
1               0                0    

In [3]:
# Evaluation function
def evaluation(y_test, y_pred):
    print('Accuracy: '  + str(metrics.accuracy_score(y_test, y_pred)))
    print('Recall: ' + str(metrics.recall_score(y_test, y_pred)))
    print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred)))
    print('Precision: ' + str(metrics.precision_score(y_test, y_pred)))

In [4]:
#train test split of data
X = exp_df.drop('fetal_health', axis =1)
y = exp_df.fetal_health

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=1)

In [5]:
#standared scaler for predicting features
scaler = StandardScaler()  
scaler.fit(X_train)

StandardScaler()

In [6]:
#Used smote to oversample minority class
sm = SMOTE(random_state=25)
smX_train, smy_train = sm.fit_sample(X_train, y_train)

In [7]:
#baseline KNN with class imbalance
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [8]:
y_pred = knn.predict(X_test)

In [9]:
#prediction metrics and confusion matrix of base KNN with class imbalance
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[396  13]
 [ 31  92]]
Accuracy: 0.9172932330827067
Recall: 0.9682151589242054
F1 Score: 0.9473684210526316
Precision: 0.927400468384075


In [10]:
#Base KNN model with Smote oversampled class
smknn = KNeighborsClassifier(n_neighbors=1)
smknn.fit(smX_train,smy_train)


KNeighborsClassifier(n_neighbors=1)

In [11]:
y_pred = smknn.predict(X_test)

In [12]:
#Prediction metrics and confusion matrix of smote base KNN
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[392  17]
 [ 27  96]]
Accuracy: 0.9172932330827067
Recall: 0.9584352078239609
F1 Score: 0.9468599033816426
Precision: 0.9355608591885441


In [13]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

/Users/heymanjake/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [14]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[385  24]
 [ 41  82]]
Accuracy: 0.8778195488721805
Recall: 0.941320293398533
F1 Score: 0.9221556886227544
Precision: 0.903755868544601


In [15]:
smlr = LogisticRegression(solver='liblinear')
smlr.fit(smX_train,smy_train)
y_predsm = smlr.predict(X_test)

In [16]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_predsm)

[[385  24]
 [ 41  82]]
Accuracy: 0.8853383458646616
Recall: 0.8801955990220048
F1 Score: 0.9218950064020486
Precision: 0.967741935483871


In [17]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",lr.coef_.transpose())

coef_table_2 = pd.DataFrame(list(smX_train.columns)).copy()
coef_table_2.insert(len(coef_table_2.columns),'sm_Coefs',smlr.coef_.transpose())

smote_vs_coef = pd.concat([coef_table,coef_table_2],axis=1)
smote_vs_coef.columns = ['features','Coefs','del','sm_Coefs']
del smote_vs_coef['del']
smote_vs_coef

features     Coefs  sm_Coefs
0                                      baseline value  0.113120  0.112113
1                                       accelerations -0.003969 -0.224252
2                                      fetal_movement  0.010522  0.313262
3                                uterine_contractions -0.005162 -0.055485
4                                 light_decelerations -0.002154 -0.036389
5                            prolongued_decelerations  0.000782  0.044586
6                     abnormal_short_term_variability  0.066839  0.084350
7                mean_value_of_short_term_variability -0.693801 -0.626913
8   percentage_of_time_with_abnormal_long_term_var...  0.037477  0.039607
9                 mean_value_of_long_term_variability  0.028837  0.045947
10                                    histogram_width -0.013946 -0.009616
11                                      histogram_min  0.006153 -0.001040
12                                      histogram_max -0.007793 -0.010656
13                          histogram_number_of_peaks  0.244309  0.200837
14                                     histogram_mode -0.023229 -0.009779
15                                     histogram_mean  0.032644 -0.059707
16                                   histogram_median -0.151405 -0.031339
17                                 histogram_variance  0.034358  0.045463
18                               uterine_cont_per_min -0.309725 -3.329097
19                                       total_change  0.039740  0.062281
20                                  sqrt_total_change -0.047973 -1.245735
21                                     hist_zeros_1.0  0.062708 -0.514483
22                                     hist_zeros_2.0  0.019549 -0.583633
23                                     hist_zeros_3.0 -0.002612 -1.085404
24                                     hist_zeros_4.0  0.017099  0.384853
25                                     hist_zeros_5.0 -0.002186 -0.626686
26                                     hist_zeros_7.0  0.000000  0.000000
27                                     hist_zeros_8.0  0.010689  0.195844
28                                    hist_zeros_10.0 -0.000754 -0.629847
29                                  hist_tendancy_0.0 -0.074347 -0.752577
30                                  hist_tendancy_1.0  0.089237 -1.254315
31                                    sev_decel_0.001 -0.003674 -0.238835
32                                        quant_acc_1 -0.228908 -3.312252
33                                  quant_light_dec_1 -0.334317 -1.669820
34                                  quant_hist_mean_1 -0.453605 -2.735225
35                                  quant_hist_mean_2 -0.247558 -2.348351
36                                  quant_hist_mean_3 -0.345706 -2.624426
37                                  quant_hist_mean_4  0.054543 -1.194180
38                                  quant_hist_mean_5  0.415893 -0.125200
39                                  quant_hist_mean_6  0.580439  0.816205

In [114]:
bag_log = BaggingClassifier(
    base_estimator=LogisticRegression(
        random_state=1),n_estimators=200,
    max_samples=.85,
    max_features=10,oob_score=True,
    n_jobs=-1,verbose=1)

In [115]:
bag_log.fit(smX_train, smy_train)

[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 out of   8 | elapsed:    3.3s remaining:    9.9s
[Parallel(n_jobs=8)]: Done   8 out of   8 | elapsed:    3.3s finished


BaggingClassifier(base_estimator=LogisticRegression(random_state=1),
                  max_features=10, max_samples=0.85, n_estimators=200,
                  n_jobs=-1, oob_score=True, verbose=1)

In [116]:
y_pred = bag_log.predict(X_test)

[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 out of   8 | elapsed:    0.0s remaining:    0.1s
[Parallel(n_jobs=8)]: Done   8 out of   8 | elapsed:    0.1s finished


In [117]:
evaluation(y_test,y_pred)

Accuracy: 0.8834586466165414
Recall: 0.8899755501222494
F1 Score: 0.9215189873417721
Precision: 0.9553805774278216


In [18]:
tree = DecisionTreeClassifier()

tree = tree.fit(X_train,y_train)

y_pred = tree.predict(X_test)

In [19]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[383  26]
 [ 18 105]]
Accuracy: 0.9172932330827067
Recall: 0.9364303178484108
F1 Score: 0.9456790123456791
Precision: 0.9551122194513716


In [20]:
smtree = DecisionTreeClassifier()
smtree.fit(smX_train,smy_train)
y_pred = smtree.predict(X_test)

In [21]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[396  13]
 [ 17 106]]
Accuracy: 0.943609022556391
Recall: 0.9682151589242054
F1 Score: 0.9635036496350364
Precision: 0.9588377723970944


In [22]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",tree.feature_importances_.transpose())

coef_table_2 = pd.DataFrame(list(smX_train.columns)).copy()
coef_table_2.insert(len(coef_table_2.columns),'sm_Coefs',tree.feature_importances_.transpose())

smote_vs_coef = pd.concat([coef_table,coef_table_2],axis=1)
smote_vs_coef.columns = ['features','importance','del','sm_importance']
del smote_vs_coef['del']
smote_vs_coef

features  importance  \
0                                      baseline value    0.033734   
1                                       accelerations    0.020453   
2                                      fetal_movement    0.016659   
3                                uterine_contractions    0.007839   
4                                 light_decelerations    0.004911   
5                            prolongued_decelerations    0.028585   
6                     abnormal_short_term_variability    0.340669   
7                mean_value_of_short_term_variability    0.107879   
8   percentage_of_time_with_abnormal_long_term_var...    0.048263   
9                 mean_value_of_long_term_variability    0.012098   
10                                    histogram_width    0.014281   
11                                      histogram_min    0.042490   
12                                      histogram_max    0.033694   
13                          histogram_number_of_peaks    0.019438   
14                                     histogram_mode    0.015507   
15                                     histogram_mean    0.173347   
16                                   histogram_median    0.011743   
17                                 histogram_variance    0.010128   
18                               uterine_cont_per_min    0.009152   
19                                       total_change    0.037034   
20                                  sqrt_total_change    0.008482   
21                                     hist_zeros_1.0    0.000000   
22                                     hist_zeros_2.0    0.000000   
23                                     hist_zeros_3.0    0.000000   
24                                     hist_zeros_4.0    0.003614   
25                                     hist_zeros_5.0    0.000000   
26                                     hist_zeros_7.0    0.000000   
27                                     hist_zeros_8.0    0.000000   
28                                    hist_zeros_10.0    0.000000   
29                                  hist_tendancy_0.0    0.000000   
30                                  hist_tendancy_1.0    0.000000   
31                                    sev_decel_0.001    0.000000   
32                                        quant_acc_1    0.000000   
33                                  quant_light_dec_1    0.000000   
34                                  quant_hist_mean_1    0.000000   
35                                  quant_hist_mean_2    0.000000   
36                                  quant_hist_mean_3    0.000000   
37                                  quant_hist_mean_4    0.000000   
38                                  quant_hist_mean_5    0.000000   
39                                  quant_hist_mean_6    0.000000   

    sm_importance  
0        0.033734  
1        0.020453  
2        0.016659  
3        0.007839  
4        0.004911  
5        0.028585  
6        0.340669  
7        0.107879  
8        0.048263  
9        0.012098  
10       0.014281  
11       0.042490  
12       0.033694  
13       0.019438  
14       0.015507  
15       0.173347  
16       0.011743  
17       0.010128  
18       0.009152  
19       0.037034  
20       0.008482  
21       0.000000  
22       0.000000  
23       0.000000  
24       0.003614  
25       0.000000  
26       0.000000  
27       0.000000  
28       0.000000  
29       0.000000  
30       0.000000  
31       0.000000  
32       0.000000  
33       0.000000  
34       0.000000  
35       0.000000  
36       0.000000  
37       0.000000  
38       0.000000  
39       0.000000

In [23]:
rfc = RandomForestClassifier(random_state =1, n_estimators= 50, max_depth = 3, n_jobs =-1,verbose=1)
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  50 out of  50 | elapsed:    0.0s finished


In [24]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[402   7]
 [ 46  77]]
Accuracy: 0.900375939849624
Recall: 0.9828850855745721
F1 Score: 0.9381563593932323
Precision: 0.8973214285714286


In [25]:
smrfc = RandomForestClassifier()
smrfc.fit(smX_train,smy_train)
y_pred = smrfc.predict(X_test)

In [26]:
print(confusion_matrix(y_test, y_pred))
evaluation(y_test, y_pred)

[[400   9]
 [ 17 106]]
Accuracy: 0.9511278195488722
Recall: 0.9779951100244498
F1 Score: 0.9685230024213076
Precision: 0.9592326139088729


In [79]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",rfc.feature_importances_.transpose())

coef_table_2 = pd.DataFrame(list(smX_train.columns)).copy()
coef_table_2.insert(len(coef_table_2.columns),'sm_Coefs',smrfc.feature_importances_.transpose())

smote_vs_coef = pd.concat([coef_table,coef_table_2],axis=1)
smote_vs_coef.columns = ['features','importance_baseline','del','sm_importance_baseline']
del smote_vs_coef['del']
smote_vs_coef

features  importance_baseline  \
0                                      baseline value         9.926765e-03   
1                                       accelerations         1.035325e-01   
2                                      fetal_movement         4.708818e-03   
3                                uterine_contractions         1.058922e-02   
4                                 light_decelerations         6.170803e-04   
5                            prolongued_decelerations         8.764041e-02   
6                     abnormal_short_term_variability         1.576849e-01   
7                mean_value_of_short_term_variability         1.492258e-01   
8   percentage_of_time_with_abnormal_long_term_var...         8.983866e-02   
9                 mean_value_of_long_term_variability         1.227784e-02   
10                                    histogram_width         2.413741e-02   
11                                      histogram_min         3.454206e-02   
12                                      histogram_max         3.475578e-03   
13                          histogram_number_of_peaks         1.292067e-03   
14                                     histogram_mode         2.993087e-02   
15                                     histogram_mean         1.002393e-01   
16                                   histogram_median         5.230935e-02   
17                                 histogram_variance         4.127107e-02   
18                               uterine_cont_per_min         3.162570e-02   
19                                       total_change         2.676057e-02   
20                                  sqrt_total_change         1.688455e-02   
21                                     hist_zeros_1.0         4.751671e-04   
22                                     hist_zeros_2.0         0.000000e+00   
23                                     hist_zeros_3.0         0.000000e+00   
24                                     hist_zeros_4.0         0.000000e+00   
25                                     hist_zeros_5.0         0.000000e+00   
26                                     hist_zeros_7.0         0.000000e+00   
27                                     hist_zeros_8.0         0.000000e+00   
28                                    hist_zeros_10.0         0.000000e+00   
29                                  hist_tendancy_0.0         0.000000e+00   
30                                  hist_tendancy_1.0         4.129194e-04   
31                                    sev_decel_0.001         0.000000e+00   
32                                        quant_acc_1         5.073501e-03   
33                                  quant_light_dec_1         2.024508e-03   
34                                  quant_hist_mean_1         6.361066e-07   
35                                  quant_hist_mean_2         0.000000e+00   
36                                  quant_hist_mean_3         2.716066e-04   
37                                  quant_hist_mean_4         1.834956e-04   
38                                  quant_hist_mean_5         9.625095e-04   
39                                  quant_hist_mean_6         2.085230e-03   

    sm_importance_baseline  
0             2.031403e-02  
1             1.037052e-01  
2             1.489257e-02  
3             2.515098e-02  
4             7.622728e-03  
5             5.389957e-02  
6             1.612922e-01  
7             1.024083e-01  
8             7.143558e-02  
9             1.827732e-02  
10            2.838014e-02  
11            4.008772e-02  
12            2.120294e-02  
13            1.326071e-02  
14            5.189639e-02  
15            6.762919e-02  
16            5.244026e-02  
17            4.058513e-02  
18            2.630329e-02  
19            2.105117e-02  
20            1.908690e-02  
21            1.054879e-03  
22            5.237246e-04  
23            4.298791e-04  
24            2.811711e-04  
25            2.162012e-05  
26            0.000000e+00  
27            7.324501e-07  
28   

In [72]:
parameters = {
    'n_estimators': [25,50,100,300,500],
    'criterion' : ['gini','entropy'],
    'max_depth' : [8,9,10,11,12],
    'max_features' : ['sqrt'],
    'min_weight_fraction_leaf' : [0,0.1,0.3,0.5],
    
    
    
}

In [73]:
grid_tree=GridSearchCV(RandomForestClassifier(), parameters, cv=15, scoring='f1', verbose=1, n_jobs=-1)

In [74]:
grid_tree.fit(smX_train, smy_train)

Fitting 15 folds for each of 200 candidates, totalling 3000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    4.0s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:   21.5s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:   48.0s
[Parallel(n_jobs=-1)]: Done 784 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 1234 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 1784 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-1)]: Done 2434 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:  5.5min finished


GridSearchCV(cv=15, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [8, 9, 10, 11, 12],
                         'max_features': ['sqrt'],
                         'min_weight_fraction_leaf': [0, 0.1, 0.3, 0.5],
                         'n_estimators': [25, 50, 100, 300, 500]},
             scoring='f1', verbose=1)

In [75]:

print(grid_tree.best_score_)

print(grid_tree.best_params_)


print(grid_tree.best_estimator_)



0.9762215043444111
{'criterion': 'gini', 'max_depth': 11, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0, 'n_estimators': 500}
RandomForestClassifier(max_depth=11, max_features='sqrt',
                       min_weight_fraction_leaf=0, n_estimators=500)


In [76]:
y_pred = grid_tree.best_estimator_.predict(X_test)
evaluation(y_test,y_pred)

Accuracy: 0.9492481203007519
Recall: 0.9755501222493888
F1 Score: 0.9672727272727273
Precision: 0.9591346153846154


In [77]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",grid_tree.best_estimator_.feature_importances_.transpose())

In [85]:
coef_table.columns = ['features','grid_search_importance']
del coef_table['features']

In [87]:
best_features_rfc = pd.concat([smote_vs_coef,coef_table],axis=1)

In [88]:
best_features_rfc

features  importance_baseline  \
0                                      baseline value         9.926765e-03   
1                                       accelerations         1.035325e-01   
2                                      fetal_movement         4.708818e-03   
3                                uterine_contractions         1.058922e-02   
4                                 light_decelerations         6.170803e-04   
5                            prolongued_decelerations         8.764041e-02   
6                     abnormal_short_term_variability         1.576849e-01   
7                mean_value_of_short_term_variability         1.492258e-01   
8   percentage_of_time_with_abnormal_long_term_var...         8.983866e-02   
9                 mean_value_of_long_term_variability         1.227784e-02   
10                                    histogram_width         2.413741e-02   
11                                      histogram_min         3.454206e-02   
12                                      histogram_max         3.475578e-03   
13                          histogram_number_of_peaks         1.292067e-03   
14                                     histogram_mode         2.993087e-02   
15                                     histogram_mean         1.002393e-01   
16                                   histogram_median         5.230935e-02   
17                                 histogram_variance         4.127107e-02   
18                               uterine_cont_per_min         3.162570e-02   
19                                       total_change         2.676057e-02   
20                                  sqrt_total_change         1.688455e-02   
21                                     hist_zeros_1.0         4.751671e-04   
22                                     hist_zeros_2.0         0.000000e+00   
23                                     hist_zeros_3.0         0.000000e+00   
24                                     hist_zeros_4.0         0.000000e+00   
25                                     hist_zeros_5.0         0.000000e+00   
26                                     hist_zeros_7.0         0.000000e+00   
27                                     hist_zeros_8.0         0.000000e+00   
28                                    hist_zeros_10.0         0.000000e+00   
29                                  hist_tendancy_0.0         0.000000e+00   
30                                  hist_tendancy_1.0         4.129194e-04   
31                                    sev_decel_0.001         0.000000e+00   
32                                        quant_acc_1         5.073501e-03   
33                                  quant_light_dec_1         2.024508e-03   
34                                  quant_hist_mean_1         6.361066e-07   
35                                  quant_hist_mean_2         0.000000e+00   
36                                  quant_hist_mean_3         2.716066e-04   
37                                  quant_hist_mean_4         1.834956e-04   
38                                  quant_hist_mean_5         9.625095e-04   
39                                  quant_hist_mean_6         2.085230e-03   

    sm_importance_baseline  grid_search_importance  
0             2.031403e-02            9.926765e-03  
1             1.037052e-01            1.035325e-01  
2             1.489257e-02            4.708818e-03  
3             2.515098e-02            1.058922e-02  
4             7.622728e-03            6.170803e-04  
5             5.389957e-02            8.764041e-02  
6             1.612922e-01            1.576849e-01  
7             1.024083e-01            1.492258e-01  
8             7.143558e-02            8.983866e-02  
9             1.827732e-02            1.227784e-02  
10            2.838014e-02            2.413741e-02  
11            4.008772e-02            3.454206e-02  
12            2.120294e-02            3.475578e-03  
13            1.326071e-02            1.292067e-03  
14            5.189639e-02            2.993087e-02 

In [95]:
best_features_rfc['coef_X_10'] = best_features_rfc.grid_search_importance*10

In [97]:
best_features_rfc

features  importance_baseline  \
0                                      baseline value         9.926765e-03   
1                                       accelerations         1.035325e-01   
2                                      fetal_movement         4.708818e-03   
3                                uterine_contractions         1.058922e-02   
4                                 light_decelerations         6.170803e-04   
5                            prolongued_decelerations         8.764041e-02   
6                     abnormal_short_term_variability         1.576849e-01   
7                mean_value_of_short_term_variability         1.492258e-01   
8   percentage_of_time_with_abnormal_long_term_var...         8.983866e-02   
9                 mean_value_of_long_term_variability         1.227784e-02   
10                                    histogram_width         2.413741e-02   
11                                      histogram_min         3.454206e-02   
12                                      histogram_max         3.475578e-03   
13                          histogram_number_of_peaks         1.292067e-03   
14                                     histogram_mode         2.993087e-02   
15                                     histogram_mean         1.002393e-01   
16                                   histogram_median         5.230935e-02   
17                                 histogram_variance         4.127107e-02   
18                               uterine_cont_per_min         3.162570e-02   
19                                       total_change         2.676057e-02   
20                                  sqrt_total_change         1.688455e-02   
21                                     hist_zeros_1.0         4.751671e-04   
22                                     hist_zeros_2.0         0.000000e+00   
23                                     hist_zeros_3.0         0.000000e+00   
24                                     hist_zeros_4.0         0.000000e+00   
25                                     hist_zeros_5.0         0.000000e+00   
26                                     hist_zeros_7.0         0.000000e+00   
27                                     hist_zeros_8.0         0.000000e+00   
28                                    hist_zeros_10.0         0.000000e+00   
29                                  hist_tendancy_0.0         0.000000e+00   
30                                  hist_tendancy_1.0         4.129194e-04   
31                                    sev_decel_0.001         0.000000e+00   
32                                        quant_acc_1         5.073501e-03   
33                                  quant_light_dec_1         2.024508e-03   
34                                  quant_hist_mean_1         6.361066e-07   
35                                  quant_hist_mean_2         0.000000e+00   
36                                  quant_hist_mean_3         2.716066e-04   
37                                  quant_hist_mean_4         1.834956e-04   
38                                  quant_hist_mean_5         9.625095e-04   
39                                  quant_hist_mean_6         2.085230e-03   

    sm_importance_baseline  grid_search_importance  coef_X_10  
0             2.031403e-02            9.926765e-03   0.099268  
1             1.037052e-01            1.035325e-01   1.035325  
2             1.489257e-02            4.708818e-03   0.047088  
3             2.515098e-02            1.058922e-02   0.105892  
4             7.622728e-03            6.170803e-04   0.006171  
5             5.389957e-02            8.764041e-02   0.876404  
6             1.612922e-01            1.576849e-01   1.576849  
7             1.024083e-01            1.492258e-01   1.492258  
8             7.143558e-02            8.983866e-02   0.898387  
9             1.827732e-02            1.227784e-02   0.122778  
10            2.838014e-02            2.413741e-02   0.241374  
11            4.008772e-02            3.454206e-02   0.345421  
12            

In [99]:
xgb.XGBClassifier()

XGBClassifier()

In [103]:
xg_clf = xgb.XGBClassifier(objective ='binary:logistic', 
                           colsample_bytree = 0.75, 
                           subsample = 0.85,
                           learning_rate = 0.1,
                           max_depth = 11, 
                           alpha = 1, 
                           n_estimators = 1000,
                          verbose=1, n_jobs=-1)

In [104]:
xg_clf.fit(smX_train,smy_train)

XGBClassifier(alpha=1, colsample_bytree=0.75, max_depth=11, n_estimators=1000,
              n_jobs=-1, subsample=0.85, verbose=1)

In [106]:
y_pred = xg_clf.predict(X_test)

In [107]:
evaluation(y_test,y_pred)

Accuracy: 0.9642857142857143
Recall: 0.9902200488997555
F1 Score: 0.97708082026538
Precision: 0.9642857142857143


In [108]:
coef_table = pd.DataFrame(list(X_train.columns)).copy()
coef_table.insert(len(coef_table.columns),"Coefs",xg_clf.feature_importances_.transpose())

In [109]:
coef_table

0     Coefs
0                                      baseline value  0.015132
1                                       accelerations  0.169203
2                                      fetal_movement  0.016855
3                                uterine_contractions  0.020800
4                                 light_decelerations  0.015470
5                            prolongued_decelerations  0.099882
6                     abnormal_short_term_variability  0.149758
7                mean_value_of_short_term_variability  0.024495
8   percentage_of_time_with_abnormal_long_term_var...  0.022075
9                 mean_value_of_long_term_variability  0.008179
10                                    histogram_width  0.008700
11                                      histogram_min  0.025074
12                                      histogram_max  0.024256
13                          histogram_number_of_peaks  0.012114
14                                     histogram_mode  0.041893
15                                     histogram_mean  0.055668
16                                   histogram_median  0.014260
17                                 histogram_variance  0.014404
18                               uterine_cont_per_min  0.027773
19                                       total_change  0.008287
20                                  sqrt_total_change  0.010150
21                                     hist_zeros_1.0  0.024100
22                                     hist_zeros_2.0  0.000000
23                                     hist_zeros_3.0  0.000000
24                                     hist_zeros_4.0  0.000000
25                                     hist_zeros_5.0  0.000000
26                                     hist_zeros_7.0  0.000000
27                                     hist_zeros_8.0  0.000000
28                                    hist_zeros_10.0  0.000000
29                                  hist_tendancy_0.0  0.007253
30                                  hist_tendancy_1.0  0.008355
31                                    sev_decel_0.001  0.000000
32                                        quant_acc_1  0.000000
33                                  quant_light_dec_1  0.010097
34                                  quant_hist_mean_1  0.017187
35                                  quant_hist_mean_2  0.013594
36                                  quant_hist_mean_3  0.061120
37                                  quant_hist_mean_4  0.024476
38                                  quant_hist_mean_5  0.043454
39                                  quant_hist_mean_6  0.005938